document.body.style.backgroundImage = "url('https://static.vecteezy.com/system/resources/thumbnails/003/087/695/original/virtual-studio-style-news-background-free-video.jpg')";
document.body.style.fontFamily="Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
document.querySelector("h1").style.color = "burlywood";
document.querySelector("h1").style.textAlign = "center";
document.querySelector("h1").style.padding = "2rem";
document.querySelector("h1").style.fontFamily = "Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
document.querySelector("h2").style.backgroundColor = "#ff634764";
document.querySelector("h2").style.textAlign = "center";
document.querySelector("h2").style.fontFamily = "Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
document.querySelector("h3").style.textAlign = "center";
document.querySelector("h3").style.padding = "2rem";
document.querySelector("h3").style.fontFamily = "Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
document.querySelector("h3").style.fontSize = "20px"
document.querySelector("h3").style.color = "burlywood";
const nodeList = document.querySelectorAll("p");
for (let i = 0; i < nodeList.length; i++) {
  nodeList[i].style.fontFamily = "Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif";
  nodeList[i].style.fontSize = "20px"
  nodeList[i].style.color = "white";
  nodeList[i].style.textAlign = "center";
}
document.querySelector("table").style.color = "white";
//document.querySelector("table").style.textAlign = "center";
document.querySelector(".DIV1").style.display = "flex";
document.querySelector(".DIV1").style.justifyContent = "center";
document.querySelector("table").style.fontFamily = "Times New Roman', Times, serif";
//document.getElementsByClassName("centerTable").style.marginLeft= "auto";
//document.getElementsByClassName("centerTable").style.marginRight = "auto";
document.querySelector("td").style.textAlign = "center";
document.querySelector("td").style.color = "white";
document.querySelector("header").style.textAlign = "center";
document.querySelector("header").style.font = "bold";
document.querySelector("footer").style.display = "flex";
document.querySelector("footer").style.justifyContent = "center";
document.querySelector("footer").style.padding = "7px";
document.querySelector("footer").style.backgroundColor = "#1e9fd2";
document.querySelector("figcaption").style.textAlign = "center";
document.querySelector("figcaption").style.color = "#fff";
document.querySelector("cite").style.color = "#fff";
//document.getElementsByClassName("news").style.margin = "3rem";
// document.getElementsByClassName("news").style.padding = "3rem";
// document.getElementsByClassName("news").style.font = "2rem";
// document.getElementsByClassName("news > h3, climate").style.fontFamily = "Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
// document.getElementsByClassName("news > h3, climate").style.margin = "5rem";
// document.getElementsByClassName("news > h3, climate").style.padding = "3rem";
// document.getElementsByClassName("news > h3, climate").style.fontSize = "1.2rem";
// document.getElementsByClassName("climate").style.background = "right/contain content-box border-box no-repeat\r\n   url('https://ak2.picdn.net/shutterstock/videos/21937012/thumb/1.jpg') rgba(255, 255, 255, 0.734)";
// document.getElementsByClassName("burlywood").style.color = "burlywood";